# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b91251640ed7068d64a2f4a14c86bf40192683bbbcb526dae1074cd57e690fca9c412d0ce223fa2748bbde929fc800ad423214641091efd56ac2646f3c13778d

test:
  secret_key_base: d7037409ef67c463c7b2da1b07a1c769d50209ec7a6fd64af34366ceb18bf36531252eff2fa1a7eb966ed2a3d00af65ce70146510138b7baba24c08cf5264ea1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
